/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp -c Adaptor -a adaptor:adaptor.cpp org.foo.test.xml
 *
 * qdbusxml2cpp is Copyright (C) 2015 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef ADAPTOR_H_1467270183
#define ADAPTOR_H_1467270183

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;

/*
 * Adaptor class for interface org.foo.test
 */
class Adaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "org.foo.test")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"org.foo.test\">\n"
"    <method name=\"getMap\">\n"
"      <arg direction=\"out\" type=\"a{sv}\"/>\n"
"      <annotation value=\"QVariantMap\" name=\"org.qtproject.QtDBus.QtTypeName.Out0\"/>\n"
"    </method>\n"
"  </interface>\n"
        "")
public:
    Adaptor(QObject *parent);
    virtual ~Adaptor();

public: // PROPERTIES
public Q_SLOTS: // METHODS
    QVariantMap getMap();
Q_SIGNALS: // SIGNALS
};

#endif
