/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp -c Adaptor -a adaptor:adaptor.cpp org.foo.test.xml
 *
 * qdbusxml2cpp is Copyright (C) 2015 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "adaptor.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class Adaptor
 */

Adaptor::Adaptor(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

Adaptor::~Adaptor()
{
    // destructor
}

QVariantMap Adaptor::getMap()
{
    // handle method call org.foo.test.getMap
    QVariantMap out0;
    QMetaObject::invokeMethod(parent(), "getMap", Q_RETURN_ARG(QVariantMap, out0));
    return out0;
}

