/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp -m -a baradaptor -i test.h -l Test ./org.kde.foo.bar.xml
 *
 * qdbusxml2cpp is Copyright (C) 2015 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "baradaptor.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class BarAdaptor
 */

BarAdaptor::BarAdaptor(Test *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

BarAdaptor::~BarAdaptor()
{
    // destructor
}

QVariantMap BarAdaptor::getMap()
{
    // handle method call org.kde.foo.bar.getMap
    return parent()->getMap();
}
