/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp -m -a baradaptor -i test.h -l Test ./org.kde.foo.bar.xml
 *
 * qdbusxml2cpp is Copyright (C) 2015 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef BARADAPTOR_H_1467708078
#define BARADAPTOR_H_1467708078

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
#include "test.h"
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;

/*
 * Adaptor class for interface org.kde.foo.bar
 */
class BarAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "org.kde.foo.bar")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"org.kde.foo.bar\">\n"
"    <signal name=\"update\"/>\n"
"    <method name=\"getMap\">\n"
"      <arg direction=\"out\" type=\"a{sv}\"/>\n"
"      <annotation value=\"QVariantMap\" name=\"org.qtproject.QtDBus.QtTypeName.Out0\"/>\n"
"    </method>\n"
"  </interface>\n"
        "")
public:
    BarAdaptor(Test *parent);
    virtual ~BarAdaptor();

    inline Test *parent() const
    { return static_cast<Test *>(QObject::parent()); }

public: // PROPERTIES
public Q_SLOTS: // METHODS
    QVariantMap getMap();
Q_SIGNALS: // SIGNALS
    void update();
};

#endif
